services:
  profile-manage-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: profile-manage-db
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Admin123
    volumes:
      - mssql-pv:/var/opt/mssql
  service:
    image: profile-manage
    container_name: profile-manage-service
    ports:
      - 5005:80
    environment:
      DB_USERNAME:  sa
      DB_PASSWORD:  Admin123
      DB_SERVER:    profile-manage-db
      GRPC_PORT:    666
      
volumes: 
  mssql-pv: