apiVersion: apps/v1
kind: Deployment
metadata:
  name: "mongo-express-depl"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express-container
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: "root"
            - name: ME_CONFIG_MONGODB_SERVER
              value: "10.100.218.238"
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-clusterip
spec:
  type: ClusterIP
  selector:
    app: mongo-express
  ports:
    - name: mongo-express
      port: 8081
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-srv
spec:
  type: NodePort
  selector:
    app: mongo-express
  ports:
    - name: mongo-express
      port: 8081
      protocol: TCP
    
                
    
  