apiVersion: apps/v1
kind: Deployment

metadata:
  name: "mongo-depl"
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo-container
          image: mongo:5.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-password
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - mountPath: /data/db 
              name: mongo-pv
      volumes:
        - name: mongo-pv
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - name: mongo
      port: 27017
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-srv
spec:
  type: NodePort
  selector:
    app: mongo
  ports:
    - name: mongo
      port: 27017
      protocol: TCP
