apiVersion: v1
kind: Service
metadata:
  name: profile-manage-db-nodeport
spec:
  type: NodePort
  selector:
    app: profile-manage-db
  ports:
    - name: profile-manage-db
      port: 1433
      targetPort: 1433
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: profile-manage-srv-nodeport
spec:
  type: NodePort
  selector:
    app: profile-manage-srv
  ports:
    - name: profile-manage-srv
      port: 6001
      targetPort: 80